# Generated by Django 4.1.7 on 2023-03-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Day", models.CharField(max_length=2000)),
            ],
        ),
        migrations.RemoveField(model_name="package", name="detailed_itinerary",),
        migrations.RemoveField(model_name="package", name="extra1",),
        migrations.RemoveField(model_name="package", name="extra2",),
        migrations.RemoveField(model_name="package", name="days",),
        migrations.AddField(
            model_name="package",
            name="days",
            field=models.ManyToManyField(blank=True, null=True, to="main.day"),
        ),
    ]
