# Generated by Django 4.0.2 on 2023-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight_booking',
            name='return_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
