# Generated by Django 4.1.7 on 2023-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_day_remove_package_detailed_itinerary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="detailed_itenerary",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.RemoveField(model_name="package", name="days",),
        migrations.DeleteModel(name="Day",),
        migrations.AddField(
            model_name="package",
            name="days",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="1",
                max_length=100,
            ),
        ),
    ]
