# Generated by Django 4.0.2 on 2023-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_flight_booking_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='departure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight_booking',
            name='return_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
