# Generated by Django 4.1.7 on 2023-03-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_package_detailed_itenerary_remove_package_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destination", old_name="name", new_name="destination",
        ),
        migrations.AlterField(
            model_name="package",
            name="detailed_itenerary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
