# Generated by Django 4.1.7 on 2023-03-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_name_destination_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="cancellation_policy",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="exclusive",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="hotel_details",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="inclusive",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="terms_and_conditions",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
