# Generated by Django 4.1.7 on 2023-03-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_package_cancellation_policy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
            ],
        ),
    ]
