# Generated by Django 4.0.2 on 2023-06-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_lead_created_remove_lead_updated_lead_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_booking',
            name='leads',
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ManyToManyField(to='main.Flight_booking')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flite_lead', to='main.lead')),
            ],
        ),
    ]
