# Generated by Django 4.0.2 on 2023-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_flight_booking_leads_flightbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='departure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight_booking',
            name='return_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
