# Generated by Django 4.1.7 on 2023-03-23 08:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_whatsappnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="alternatemobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=20, null=True, region=None
            ),
        ),
    ]
