# Generated by Django 4.1.7 on 2023-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_customer_alternatemobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="pan",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
