# Generated by Django 4.0.2 on 2023-06-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_flight_booking_departure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='customized_package',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='forex',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='group',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='hotel_booking',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='other',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='packagee',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='sightseen',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='train',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='travel_insurance',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='visa_booking',
            name='leads',
        ),
        migrations.CreateModel(
            name='VisaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_lead', to='main.lead')),
                ('visa', models.ManyToManyField(to='main.Visa_booking')),
            ],
        ),
        migrations.CreateModel(
            name='TravelInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_insurance_lead', to='main.lead')),
                ('travelinsurance', models.ManyToManyField(to='main.Travel_insurance')),
            ],
        ),
        migrations.CreateModel(
            name='LeadTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_lead', to='main.lead')),
                ('transport', models.ManyToManyField(to='main.Transport')),
            ],
        ),
        migrations.CreateModel(
            name='LeadTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_lead', to='main.lead')),
                ('train', models.ManyToManyField(to='main.Train')),
            ],
        ),
        migrations.CreateModel(
            name='LeadSightseen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightseen_lead', to='main.lead')),
                ('sightseen', models.ManyToManyField(to='main.Sightseen')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_lead', to='main.lead')),
                ('passport', models.ManyToManyField(to='main.Passport')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_lead', to='main.lead')),
                ('package', models.ManyToManyField(to='main.Packagee')),
            ],
        ),
        migrations.CreateModel(
            name='LeadOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lead', to='main.lead')),
                ('other', models.ManyToManyField(to='main.Other')),
            ],
        ),
        migrations.CreateModel(
            name='LeadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(to='main.Group')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lead', to='main.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadForex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forex', models.ManyToManyField(to='main.Forex')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_lead', to='main.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise', models.ManyToManyField(to='main.Cruise')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruise_lead', to='main.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ManyToManyField(to='main.Bus')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_lead', to='main.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.ManyToManyField(to='main.Adventure')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_lead', to='main.lead')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ManyToManyField(to='main.Hotel_booking')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_lead', to='main.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizedpackage', models.ManyToManyField(to='main.Customized_Package')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_package_lead', to='main.lead')),
            ],
        ),
    ]
